In [1]:
import numpy as np
import torch

In [3]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [8]:
x_ones = torch.rand_like(x_data, dtype=torch.float)
x_ones

tensor([[0.2902, 0.4829],
        [0.8795, 0.6127]])

Tuples are a way of storing data that is ordered and unchangable.

In [15]:
shape = (2, 3)

rand_tensor = torch.zeros(shape)
rand_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
tensor = torch.rand(3, 4)

print(tensor.dtype)
print(tensor.shape)
print(tensor.device)

torch.float32
torch.Size([3, 4])
cpu


In [18]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print('done')

In [19]:
tensor = torch.ones(4, 4)

tensor[:, 1] = 0

tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [26]:
# dim=1 places them side by side, dim=0 places them on top of eachother
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t2 = t1*t1
t2

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x12 and 4x12)

In [29]:
t1 = tensor.matmul(tensor.T)
t1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

Changing the tensors will reflect in the numpy array also if they are bridged

In [31]:
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [33]:
prediction = model(data)
prediction

tensor([[-7.9952e-02, -2.1826e-01, -4.9330e-01, -1.5342e+00, -5.0970e-01,
         -1.1295e-01, -4.8042e-01,  5.6218e-01,  5.6653e-01, -8.3602e-01,
         -5.4272e-01, -3.5493e-01,  2.2454e-01, -7.8269e-01, -6.6449e-01,
         -3.7645e-01, -7.4985e-01, -6.3539e-02, -3.7134e-01, -2.9895e-01,
         -1.2833e+00, -4.2998e-01, -1.4801e+00, -2.3828e-02, -1.2024e+00,
         -9.3552e-01, -6.0894e-01, -1.0844e+00, -8.5346e-01, -3.9148e-01,
         -6.7236e-01, -6.6981e-01, -3.3512e-01, -5.3502e-01, -3.5142e-01,
         -3.4811e-01,  8.2252e-01, -3.4022e-01, -4.5239e-01,  4.7418e-02,
         -5.4472e-01, -6.4894e-01, -9.7430e-01, -4.2582e-01, -4.3737e-01,
         -2.1231e-01, -6.9491e-01, -6.1204e-01, -1.2286e+00, -1.2928e+00,
         -4.5483e-01,  4.2866e-01, -2.4230e-01, -5.5055e-01, -2.3337e-01,
         -9.6780e-01, -3.2294e-01, -1.2839e+00, -2.6375e-01, -2.6034e-01,
          6.7618e-01,  2.1543e-01,  8.1630e-02,  3.9193e-01, -6.2179e-01,
         -1.6478e-01, -2.4509e-01, -4.

In [34]:
loss = (prediction - labels).sum()
loss.backward()

In [35]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)


In [36]:
optim.step()

In [38]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [39]:
Q = 3*a**3 - b**2

In [40]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.module):

    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)